<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Components\Success.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlusMoney.API\PlusMoney.API.csproj" />
    <PackageReference Include="Blazor.Bootstrap" Version="3.0.0" />
    <PackageReference Include="Blazored.SessionStorage" Version="2.4.0" />
    <PackageReference Include="NetcodeHub.Packages.Components.Toast" Version="1.0.0" />
	<PackageReference Include="Radzen.Blazor" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Components\Pages\NovoUsuario.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Components\Pages\Perfil.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Components\Pages\LoginPage.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Components\Success.razor" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Components\Success.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Components\Pages\Success.razor" />
  </ItemGroup>

</Project>
